from setuptools import find_packages, setup

setup(
    name='django-partners',
    description='Django pluggable app for partnership programs. Enables to share with a partner a percent of incomes that are generated by any user in the system.',
    long_description='',
    version='0.1',
    packages=['partners',],
    license='MIT',
    author='Krzysztof Dorosz',
    author_email='cypreess@gmail.com',
    package_data={
        'partners': [
            'templates/partners/*.html',
        ],
    }
)